return {
  aquilo_dangerous = require("planets.generated.aquilo_dangerous"),
  aquilo_dwarf = require("planets.generated.aquilo_dwarf"),
  aquilo_ribon = require("planets.generated.aquilo_ribon"),
  aquilo_rich = require("planets.generated.aquilo_rich"),
  fulgora_dangerous = require("planets.generated.fulgora_dangerous"),
  fulgora_dwarf = require("planets.generated.fulgora_dwarf"),
  fulgora_ribon = require("planets.generated.fulgora_ribon"),
  fulgora_rich = require("planets.generated.fulgora_rich"),
  gleba_dangerous = require("planets.generated.gleba_dangerous"),
  gleba_dwarf = require("planets.generated.gleba_dwarf"),
  gleba_ribon = require("planets.generated.gleba_ribon"),
  gleba_rich = require("planets.generated.gleba_rich"),
  nauvis_dangerous = require("planets.generated.nauvis_dangerous"),
  nauvis_dwarf = require("planets.generated.nauvis_dwarf"),
  nauvis_ribon = require("planets.generated.nauvis_ribon"),
  nauvis_rich = require("planets.generated.nauvis_rich"),
  vulcanus_dangerous = require("planets.generated.vulcanus_dangerous"),
  vulcanus_dwarf = require("planets.generated.vulcanus_dwarf"),
  vulcanus_ribon = require("planets.generated.vulcanus_ribon"),
  vulcanus_rich = require("planets.generated.vulcanus_rich"),
}
